{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "poc2prod.fullname" . }}-app
  labels:
    {{- include "poc2prod.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.global.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.secretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.remoteSecretName }}
{{- end }}

