{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.createClusterSecretStore }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.global.clusterSecretStoreName }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.global.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "poc2prod.apiServiceAccountName" . }}
            namespace: {{ .Release.Namespace }}
{{- end }}

